# Generated by Django 5.0 on 2024-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_end_date_remove_event_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaisedHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interests', models.TextField()),
            ],
        ),
    ]
